import {
  AlertTriangle,
  Camera,
  CheckCircle2,
  Database,
  EyeOff,
  FileText,
  HeartPulse,
  Info,
  Lock,
  Mail,
  Scale,
  Shield,
  ShieldAlert,
  ShieldCheck,
  UserCheck,
  Zap,
} from 'lucide-react';
import ScreenHeader from '../components/ScreenHeader';

export default function TermsScreen({ onNavigate, appActive, hasProfile }) {
  return (
    <main className="screen-page terms-page">
      <ScreenHeader
        eyebrow="Trust, Privacy & Disclosures"
        title="Terms of Service & Privacy Policy"
        description="Transparent operating principles, health disclaimers, and data architecture disclosures for BITS in Motion. Last updated for Smart India Hackathon 2026."
        action={
          <div className="screen-heading-actions">
            <button
              className="button button-primary"
              type="button"
              onClick={() => onNavigate(appActive && hasProfile ? 'dashboard' : 'welcome')}
            >
              Return to {appActive && hasProfile ? 'Dashboard' : 'Home'}
            </button>
          </div>
        }
      />

      {/* High-level Notice Card */}
      <div className="terms-notice-box">
        <div className="terms-notice-icon"><Info size={24} /></div>
        <div className="terms-notice-body">
          <strong>Hackathon Proof-of-Concept Disclosure</strong>
          <p>
            BITS in Motion is a student-focused fitness and on-device computer vision prototype created for Smart India Hackathon 2026. This platform is provided strictly for educational, demonstration, and personal workout tracking purposes. We believe in total transparency: no misleading compliance claims, no hidden data brokers, and honest disclosures of actual system architecture.
          </p>
        </div>
      </div>

      <div className="terms-container">
        {/* Section 1: Purpose & Acceptance */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">01</span>
            <h2>Purpose & Acceptance of Terms</h2>
          </div>
          <div className="terms-section-content">
            <p>
              By accessing or using the BITS in Motion web application, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.
            </p>
            <p>
              BITS in Motion is designed to assist college students and individuals living in limited-space accommodations (such as hostel rooms, dormitories, and apartments) in planning realistic bodyweight workouts and checking exercise form using on-device computer vision.
            </p>
          </div>
        </section>

        {/* Section 2: Medical & Fitness Disclaimer */}
        <section className="terms-section highlight-border">
          <div className="terms-section-header">
            <span className="terms-num">02</span>
            <h2>Fitness & Health Disclaimer (Not Medical Advice)</h2>
          </div>
          <div className="terms-section-content">
            <div className="terms-alert-card warning">
              <HeartPulse size={22} className="alert-icon" />
              <div>
                <strong>Important Health Advisory:</strong>
                <p>
                  BITS in Motion is <strong>NOT a medical device</strong> and does NOT provide medical advice, diagnosis, or clinical therapy. The exercises, movement cues, and estimated energy expenditure metrics generated by the software are for informational and motivational guidance only.
                </p>
              </div>
            </div>
            <ul>
              <li>
                <strong>Consult a Physician:</strong> You should always consult with a licensed healthcare professional before beginning any exercise routine, particularly if you have pre-existing cardiovascular conditions, musculoskeletal injuries, chronic illnesses, or pregnancy.
              </li>
              <li>
                <strong>Listen to Your Body:</strong> If you experience sharp pain, excessive fatigue, dizziness, lightheadedness, shortness of breath, nausea, or discomfort at any point during a session, <strong>stop exercising immediately</strong> and seek professional medical assistance if symptoms persist.
              </li>
              <li>
                <strong>Safe Environment:</strong> You are solely responsible for clearing your physical surroundings of tripping hazards, sharp furniture edges, wet surfaces, or obstruction before starting any workout.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 3: Camera Usage & On-Device Processing */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">03</span>
            <h2>Camera Usage & On-Device Vision Privacy</h2>
          </div>
          <div className="terms-section-content">
            <p>
              Camera-guided movement coaching requires browser camera access to function. Our technical architecture is designed from the ground up to guarantee strict visual privacy:
            </p>
            <div className="terms-grid-two">
              <div className="terms-subbox positive">
                <div className="subbox-title"><ShieldCheck size={18} className="text-teal" /> What We Do</div>
                <ul>
                  <li>Process camera video frames <strong>entirely inside your browser</strong> using client-side Google MediaPipe WebAssembly / WebGL models.</li>
                  <li>Calculate 33 numerical coordinates (landmarks) to measure joint angles and repetition cycles in temporary memory.</li>
                  <li>Discard video frames immediately after numerical analysis.</li>
                  <li>Release the camera hardware stream instantly when you pause, end, or exit the session.</li>
                </ul>
              </div>
              <div className="terms-subbox negative">
                <div className="subbox-title"><EyeOff size={18} className="text-danger" /> What We NEVER Do</div>
                <ul>
                  <li>We <strong>NEVER</strong> record, store, or archive your video stream or camera photographs.</li>
                  <li>We <strong>NEVER</strong> upload or stream video data to any cloud server, third party, or API.</li>
                  <li>We <strong>NEVER</strong> record background audio or room sounds.</li>
                  <li>We <strong>NEVER</strong> use facial recognition, biometric identity scanning, or iris identification.</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Section 4: Data Storage, Modes & User Isolation */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">04</span>
            <h2>Data Persistence: Guest Mode vs. Google Account</h2>
          </div>
          <div className="terms-section-content">
            <p>
              BITS in Motion supports two distinct modes of operation with strict boundaries:
            </p>
            <div className="terms-subbox">
              <h3>1. Guest Mode (100% Local Storage)</h3>
              <p>
                When using Guest Mode, your fitness profile (age, height, weight, fitness goals), generated routines, and completed workout records are saved strictly in your browser’s HTML5 <code>localStorage</code> (keys: <code>bits-motion-profile-v1</code>, <code>bits-motion-sessions-v1</code>, <code>bits-motion-plan-v1</code>). No account is created, no database records are generated, and clearing your browser storage permanently clears this data.
              </p>
            </div>
            <div className="terms-subbox">
              <h3>2. Google Account Mode (Cloud Synchronization)</h3>
              <p>
                When you choose to sign in with Google, Google Identity Services verifies your account and passes a signed JWT token to our backend. Our application stores:
              </p>
              <ul>
                <li>Your Google profile identifiers (email, account name, avatar URL).</li>
                <li>Your fitness setup preferences (fitness level, duration, location, equipment, low-impact toggle).</li>
                <li>Your completed session logs (reps counted, duration in seconds, MET-estimated calories, timestamp, and form feedback summaries).</li>
              </ul>
            </div>
            <div className="terms-subbox">
              <h3>3. Strict User Data Isolation</h3>
              <p>
                Database queries on our managed Neon PostgreSQL server enforce strict row-level ownership (e.g. <code>WHERE user_id = $authenticated_user</code>). One authenticated user cannot query, read, update, or delete another user’s workout records or profile. Furthermore, local guest data is never automatically imported or blended into an authenticated account.
              </p>
            </div>
          </div>
        </section>

        {/* Section 5: Sessions & Cookies */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">05</span>
            <h2>Authentication, Cookies & Security Practices</h2>
          </div>
          <div className="terms-section-content">
            <ul>
              <li>
                <strong>HTTP-Only Session Cookies:</strong> Authenticated sessions rely on an HTTP-only, secure, SameSite cookie containing a signed session token. This protects session tokens from client-side script inspection (mitigating XSS extraction).
              </li>
              <li>
                <strong>No Password Storage:</strong> We do not ask for, receive, or store your Google password. Authentication is mediated entirely by Google’s verified OAuth 2.0 / OpenID Connect infrastructure.
              </li>
              <li>
                <strong>SQL Injection Prevention:</strong> Database operations use parameterized queries against our Neon serverless driver to prevent SQL injection vulnerabilities.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 6: Campus Leaderboard & Alias Privacy */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">06</span>
            <h2>Opt-In Campus Leaderboard & Alias Privacy</h2>
          </div>
          <div className="terms-section-content">
            <p>
              The community leaderboard celebrates consistency across the campus community. To protect your personal privacy:
            </p>
            <ul>
              <li><strong>Strictly Opt-In:</strong> Leaderboard participation is disabled by default. You must explicitly toggle leaderboard participation on in your profile.</li>
              <li><strong>Custom Display Alias:</strong> You can define a public handle (alias). Your Google email address, real full name, and private health metrics (body weight, height, age) are NEVER shown on public rankings.</li>
              <li><strong>Non-Body Metrics:</strong> Rankings reflect only active days, completed workouts, and verified camera reps.</li>
            </ul>
          </div>
        </section>

        {/* Section 7: Accuracy Limitations of AI */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">07</span>
            <h2>Accuracy Limitations of AI & Pose Detection</h2>
          </div>
          <div className="terms-section-content">
            <p>
              Users acknowledge that artificial intelligence, computer vision, and pose landmarker algorithms are inherently subject to technical tolerances and approximations:
            </p>
            <ul>
              <li>
                <strong>Environmental Sensitivity:</strong> Accuracy of landmark tracking is heavily influenced by ambient lighting, room contrast, camera angle, distance from lens, loose clothing, and background movement.
              </li>
              <li>
                <strong>No Perfect Form Guarantee:</strong> Automated repetition counts and real-time posture feedback cues represent algorithmic heuristics, not an infallible biomechanical assessment or certified trainer’s supervision.
              </li>
              <li>
                <strong>Calorie Estimation:</strong> Calorie estimates are mathematical approximations based on published MET tables and user-entered body weight; individual metabolic rates and exertion vary significantly.
              </li>
            </ul>
          </div>
        </section>

        {/* Section 8: Scope & Certifications Disclosure */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">08</span>
            <h2>Transparent Scope & Regulatory Disclosures</h2>
          </div>
          <div className="terms-section-content">
            <p>
              To uphold absolute honesty as a hackathon submission, we explicitly state our compliance scope:
            </p>
            <div className="terms-alert-card info">
              <Info size={20} className="alert-icon" />
              <div>
                <p>
                  BITS in Motion is a student hackathon proof-of-concept. It does <strong>NOT</strong> hold formal regulatory certifications, including but not limited to: HIPAA compliance certification, GDPR regulatory audit certification, ISO/IEC 27001 certification, SOC 2 Type II audit reports, or FDA/CE medical-device clearances.
                </p>
                <p>
                  While we implement genuine security engineering practices (HTTPS transport, parameterized SQL, on-device vision, HTTP-only cookies, token verification), the software should be evaluated within the context of a student technology demonstration.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 9: Limitation of Liability */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">09</span>
            <h2>Limitation of Liability & Warranty Disclaimer</h2>
          </div>
          <div className="terms-section-content">
            <p>
              THE APPLICATION IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE DEVELOPERS, MENTORS, AND AFFILIATED INSTITUTIONS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO PERSONAL INJURY, PHYSICAL HARM, LOSS OF DATA, OR SERVICE INTERRUPTIONS ARISING OUT OF YOUR USE OF THE APPLICATION.
            </p>
          </div>
        </section>

        {/* Section 10: Changes & Contact */}
        <section className="terms-section">
          <div className="terms-section-header">
            <span className="terms-num">10</span>
            <h2>Modifications & Contact Placeholder</h2>
          </div>
          <div className="terms-section-content">
            <p>
              We reserve the right to revise or modify these terms as the hackathon prototype evolves. Updates will be reflected directly on this page.
            </p>
            <p>
              For inquiries, evaluations, or technical feedback regarding this Smart India Hackathon 2026 prototype:
            </p>
            <div className="terms-contact-card">
              <Mail size={20} />
              <div>
                <strong>Project Team — BITS in Motion</strong>
                <span>Smart India Hackathon 2026 Student Prototype</span>
              </div>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}
